services:
  - type: web
    name: discord-bot
    runtime: python
    region: oregon   # or closest to you
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PREFIX
        sync: false
      - key: DATABASE_URL
        sync: false
